# -*- coding: utf-8 -*-
"""
Демонстрационный датасет университетов и программ бакалавриата в Казахстане.

ВАЖНО: все цифры (пороги ЕНТ, стоимость, дедлайны) — ДЕМОНСТРАЦИОННЫЕ данные,
собранные вручную для прототипа хакатона. Они НЕ являются официальной
информацией и не гарантируют поступление. Перед подачей документов уточняйте
актуальные требования на официальных сайтах вузов (ссылки указаны в поле
"source"). Это сделано намеренно, в соответствии с требованием кейса не
показывать вымышленную точность без пометки о демо-данных.
"""

# Направления, из которых пользователь выбирает интересы
INTERESTS = [
    ("it", "💻 IT и программирование"),
    ("business", "📈 Бизнес и экономика"),
    ("engineering", "⚙️ Инженерия"),
    ("medicine", "🩺 Медицина"),
    ("law", "⚖️ Право"),
    ("humanities", "📚 Гуманитарные науки"),
    ("design", "🎨 Дизайн и creative"),
    ("science", "🔬 Естественные науки"),
]

# tuition_category: "grant_only" (в основном грантовые места),
#                    "mid" (есть бюджетные варианты подешевле),
#                    "high" (преимущественно платное, дорогое обучение)
PROGRAMS = [
    {
        "id": "nu",
        "name": "Nazarbayev University — School of Engineering & Digital Sciences",
        "city": "Астана",
        "fields": ["it", "engineering", "science"],
        "ent_threshold": 110,
        "tuition_category": "grant_only",
        "tuition_tenge_year": 0,  # обучение бесплатное при поступлении по гранту NU
        "languages_required": ["en"],
        "min_ielts": 6.0,
        "scholarship_note": "Собственная грантовая система NU покрывает 100% для большинства студентов (демо-оценка).",
        "deadline": "2027-01-15 (демо, уточняйте на сайте)",
        "source": "https://nu.edu.kz/admissions (демо-данные, сверяйте актуальные требования)",
        "description": "Топовый исследовательский университет с обучением на английском языке и сильной инженерной/IT школой.",
    },
    {
        "id": "kbtu",
        "name": "КБТУ — Казахстанско-Британский технический университет",
        "city": "Алматы",
        "fields": ["it", "engineering", "business"],
        "ent_threshold": 90,
        "tuition_category": "mid",
        "tuition_tenge_year": 2600000,
        "languages_required": ["en", "ru"],
        "min_ielts": 5.5,
        "scholarship_note": "Есть гранты акимата и внутренние скидки за высокий балл ЕНТ (демо-оценка).",
        "deadline": "2027-07-25 (демо, уточняйте на сайте)",
        "source": "https://kbtu.edu.kz (демо-данные, сверяйте актуальные требования)",
        "description": "Сильная связка IT/инженерия/бизнес, партнёрства с индустрией, обучение в Алматы.",
    },
    {
        "id": "sdu",
        "name": "SDU University",
        "city": "Каскелен (обл. Алматы)",
        "fields": ["it", "business", "humanities", "science"],
        "ent_threshold": 70,
        "tuition_category": "mid",
        "tuition_tenge_year": 1500000,
        "languages_required": ["en", "kz", "ru"],
        "min_ielts": 5.0,
        "scholarship_note": "Широкая грантовая программа университета при среднем и высоком балле ЕНТ (демо-оценка).",
        "deadline": "2027-07-20 (демо, уточняйте на сайте)",
        "source": "https://sdu.edu.kz (демо-данные, сверяйте актуальные требования)",
        "description": "Международная образовательная модель, доступная стоимость, кампус за городом.",
    },
    {
        "id": "kaznu",
        "name": "КазНУ им. аль-Фараби",
        "city": "Алматы",
        "fields": ["science", "humanities", "law", "medicine", "it"],
        "ent_threshold": 75,
        "tuition_category": "mid",
        "tuition_tenge_year": 900000,
        "languages_required": ["kz", "ru"],
        "min_ielts": None,
        "scholarship_note": "Крупнейший вуз страны, много госгрантов по естественнонаучным направлениям (демо-оценка).",
        "deadline": "2027-07-20 (демо, уточняйте на сайте)",
        "source": "https://kaznu.kz (демо-данные, сверяйте актуальные требования)",
        "description": "Широкий выбор направлений, классический университет с большим числом бюджетных мест.",
    },
    {
        "id": "ama",
        "name": "Almaty Management University (AlmaU)",
        "city": "Алматы",
        "fields": ["business", "design", "law"],
        "ent_threshold": 60,
        "tuition_category": "high",
        "tuition_tenge_year": 2900000,
        "languages_required": ["ru", "en"],
        "min_ielts": None,
        "scholarship_note": "Есть скидки за портфолио/эссе, но большинство мест платные (демо-оценка).",
        "deadline": "2027-08-01 (демо, уточняйте на сайте)",
        "source": "https://almau.edu.kz (демо-данные, сверяйте актуальные требования)",
        "description": "Сильная бизнес-школа и креативные направления, много практики и стартап-среды.",
    },
    {
        "id": "kaznmu",
        "name": "КазНМУ им. С.Д. Асфендиярова",
        "city": "Алматы",
        "fields": ["medicine", "science"],
        "ent_threshold": 100,
        "tuition_category": "mid",
        "tuition_tenge_year": 1800000,
        "languages_required": ["kz", "ru"],
        "min_ielts": None,
        "scholarship_note": "Ограниченное число грантов, высокий конкурс на медицинские специальности (демо-оценка).",
        "deadline": "2027-07-20 (демо, уточняйте на сайте)",
        "source": "https://kaznmu.edu.kz (демо-данные, сверяйте актуальные требования)",
        "description": "Ведущий медицинский вуз страны, высокий проходной балл, клиническая база.",
    },
    {
        "id": "satbayev",
        "name": "Satbayev University",
        "city": "Алматы",
        "fields": ["engineering", "science", "it"],
        "ent_threshold": 65,
        "tuition_category": "mid",
        "tuition_tenge_year": 1400000,
        "languages_required": ["kz", "ru"],
        "min_ielts": None,
        "scholarship_note": "Технический вуз с большим количеством грантов по инженерным специальностям (демо-оценка).",
        "deadline": "2027-07-20 (демо, уточняйте на сайте)",
        "source": "https://satbayev.university (демо-данные, сверяйте актуальные требования)",
        "description": "Исторически сильная инженерно-техническая школа, недорогое обучение.",
    },
    {
        "id": "kimep",
        "name": "KIMEP University",
        "city": "Алматы",
        "fields": ["business", "law", "humanities"],
        "ent_threshold": 85,
        "tuition_category": "high",
        "tuition_tenge_year": 3400000,
        "languages_required": ["en"],
        "min_ielts": 6.0,
        "scholarship_note": "Есть merit-стипендии за высокий IELTS/GPA (демо-оценка).",
        "deadline": "2027-06-01 (демо, уточняйте на сайте)",
        "source": "https://kimep.kz (демо-данные, сверяйте актуальные требования)",
        "description": "Обучение полностью на английском, сильная бизнес- и юридическая школа, западный формат.",
    },
    {
        "id": "turan",
        "name": "Университет Туран — Дизайн и медиа",
        "city": "Алматы",
        "fields": ["design", "humanities"],
        "ent_threshold": 55,
        "tuition_category": "mid",
        "tuition_tenge_year": 1200000,
        "languages_required": ["ru", "kz"],
        "min_ielts": None,
        "scholarship_note": "Гранты по творческому конкурсу для абитуриентов с портфолио (демо-оценка).",
        "deadline": "2027-08-05 (демо, уточняйте на сайте)",
        "source": "https://turan-edu.kz (демо-данные, сверяйте актуальные требования)",
        "description": "Доступный вход в дизайн/медиа-направления, портфолио важнее ЕНТ.",
    },
    {
        "id": "narxoz",
        "name": "Narxoz University",
        "city": "Алматы",
        "fields": ["business", "law", "it"],
        "ent_threshold": 65,
        "tuition_category": "mid",
        "tuition_tenge_year": 1700000,
        "languages_required": ["ru", "en"],
        "min_ielts": None,
        "scholarship_note": "Собственная грантовая программа при балле ЕНТ выше среднего (демо-оценка).",
        "deadline": "2027-07-25 (демо, уточняйте на сайте)",
        "source": "https://narxoz.edu.kz (демо-данные, сверяйте актуальные требования)",
        "description": "Экономика и бизнес-аналитика, партнёрства с бизнесом, кампус в Алматы.",
    },
]

CITIES = ["Алматы", "Астана", "Каскелен (обл. Алматы)", "Не важно / рассмотрю разные"]

BUDGET_OPTIONS = [
    ("grant", "🎓 Нужен грант / бюджет — платить не готов(а)"),
    ("low", "💸 До 1.5 млн ₸/год"),
    ("mid", "💰 До 3 млн ₸/год"),
    ("any", "🏦 Бюджет не ограничен"),
]

GRADE_OPTIONS = [
    ("g9", "9 класс"),
    ("g10", "10 класс"),
    ("g11", "11 класс"),
    ("grad", "Уже выпускник(ца), поступаю в этом году"),
]
